"""Infrastructure interfaces used by the public SDK and domain services."""

from __future__ import annotations

from contextlib import AbstractContextManager
from dataclasses import dataclass
from datetime import datetime
from typing import Any, BinaryIO, Iterable, Protocol

from mkb.models import Entity, Relation


@dataclass(frozen=True)
class ObjectInfo:
    """Backend-neutral object identity and metadata."""

    bucket: str
    key: str
    size: int
    etag: str | None = None
    last_modified: datetime | None = None


class Database(Protocol):
    """Minimal relational persistence lifecycle owned by one SDK client."""

    def session(self) -> AbstractContextManager[Any]: ...
    def transaction(self) -> AbstractContextManager[Any]: ...
    def check(self) -> None: ...
    def close(self) -> None: ...


class ObjectStore(Protocol):
    """Object persistence kept separate from relational repositories."""

    def put_bytes(self, bucket: str, key: str, data: bytes) -> None: ...
    def get_bytes(self, bucket: str, key: str) -> bytes: ...
    def open(self, bucket: str, key: str) -> BinaryIO: ...
    def exists(self, bucket: str, key: str) -> bool: ...
    def delete(self, bucket: str, key: str) -> None: ...
    def list(self, bucket: str, prefix: str = "") -> Iterable[ObjectInfo]: ...
    def check(self, buckets: Iterable[str] = ()) -> None: ...
    def close(self) -> None: ...


class GraphStore(Protocol):
    """Graph persistence kept distinct from relational and object storage."""

    @property
    def capabilities(self) -> frozenset[str]: ...
    def upsert_entity(self, entity: Entity) -> Entity: ...
    def get_entity(self, entity_id: str) -> Entity | None: ...
    def list_entities(self, *, type: str | None = None) -> list[Entity]: ...
    def upsert_relation(self, relation: Relation) -> Relation: ...
    def get_relation(self, relation_id: str) -> Relation | None: ...
    def list_relations(
        self, *, entity_id: str | None = None, type: str | None = None
    ) -> list[Relation]: ...
    def close(self) -> None: ...


class ModelProvider(Protocol):
    """External inference provider owned by one configured client."""

    @property
    def identity(self) -> str: ...
    @property
    def capabilities(self) -> frozenset[str]: ...
    def generate(self, prompt: str, *, parameters: dict[str, Any] | None = None) -> Any: ...
    def close(self) -> None: ...


class JobBackend(Protocol):
    """Lifecycle and capabilities for a future durable execution backend."""

    @property
    def capabilities(self) -> frozenset[str]: ...
    def close(self) -> None: ...
