"""Generate the supported typed Python API reference.

Run from the repository root with ``.venv/bin/python scripts/generate_api_reference.py``.
"""

# ruff: noqa: E402 -- local src/ must precede an older installed package.

from __future__ import annotations

import inspect
import sys
from dataclasses import MISSING, fields
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import mkb
from pydantic import BaseModel

from mkb.application_services import MaintenanceService, SettingsService
from mkb.graph import Graph
from mkb.job_service import Jobs
from mkb.managed_services import Feedback, PostProcessors, Skills
from mkb.pipelines import Pipelines
from mkb.registries import Parsers, Steps
from mkb.repositories import (
    Artifacts,
    CollectionGroups,
    Collections,
    EvidenceLinks,
    ExtractionSchemas,
    Projections,
    Records,
    Sources,
)

OUTPUT = ROOT / "docs/api-reference.md"

SERVICES = (
    ("kb.collections", Collections),
    ("kb.collections.groups", CollectionGroups),
    ("kb.sources", Sources),
    ("kb.artifacts", Artifacts),
    ("kb.records", Records),
    ("kb.schemas", ExtractionSchemas),
    ("kb.projections", Projections),
    ("kb.evidence", EvidenceLinks),
    ("kb.graph", Graph),
    ("kb.pipelines", Pipelines),
    ("kb.jobs", Jobs),
    ("kb.feedback", Feedback),
    ("kb.skills", Skills),
    ("kb.post_processors", PostProcessors),
    ("kb.parsers", Parsers),
    ("kb.steps", Steps),
    ("kb.settings", SettingsService),
    ("kb.maintenance", MaintenanceService),
)

CLIENT_METHODS = (
    "from_environment",
    "from_url",
    "initialize",
    "schema_version",
    "transaction",
    "close",
)

CLIENT_SUMMARIES = {
    "from_environment": "Create a client for the configured materials application.",
    "close": "Close client-owned resources and submitted pipeline workers.",
}


def _summary(member) -> str:
    doc = inspect.getdoc(member) or ""
    return doc.splitlines()[0] if doc else ""


def _signature(member) -> str:
    signature = inspect.signature(member)
    # Parameters beginning with an underscore are implementation controls, even when
    # they are needed for internal collaboration between public methods. Do not turn
    # them into a documented compatibility commitment.
    signature = signature.replace(
        parameters=[
            parameter
            for parameter in signature.parameters.values()
            if not parameter.name.startswith("_")
        ]
    )
    signature = str(signature)
    return signature.replace("(self, ", "(").replace("(self)", "()")


def generate() -> str:
    lines = [
        "# Generated Python API reference",
        "",
        "<!-- Generated by scripts/generate_api_reference.py; do not edit manually. -->",
        "",
        "This reference lists the supported typed root models and grouped services. ",
        "See [Python API](python-api.md) for local, PostgreSQL/MinIO, custom-pipeline, ",
        "and safe migration examples.",
        "",
        "## Public typed models",
        "",
    ]
    for name in mkb.__all__:
        member = getattr(mkb, name)
        if not inspect.isclass(member) or not issubclass(member, BaseModel):
            continue
        lines.extend((f"### `{name}`", "", _summary(member), "", "Fields:", ""))
        for field_name, field in member.model_fields.items():
            required = "required" if field.is_required() else "optional/defaulted"
            lines.append(f"- `{field_name}` — `{field.annotation!s}` ({required})")
        lines.append("")

    lines.extend(
        (
            "## Configured client",
            "",
            "### `KnowledgeBase`",
            "",
            "The portable client entry point. See [Python API](python-api.md) for "
            "installation, supported adapter injection, and lifecycle guidance.",
            "",
        )
    )
    for method_name in CLIENT_METHODS:
        method = getattr(mkb.KnowledgeBase, method_name)
        lines.extend(
            (
                f"#### `{method_name}{_signature(method)}`",
                "",
                _summary(method) or CLIENT_SUMMARIES.get(method_name, ""),
                "",
            )
        )

    lines.extend(
        ("### `MKBConfig`", "", "Immutable client configuration.", "", "Fields:", "")
    )
    for config_field in fields(mkb.MKBConfig):
        required = "required" if config_field.default is MISSING else "optional/defaulted"
        lines.append(f"- `{config_field.name}` — `{config_field.type!s}` ({required})")
    lines.append("")

    lines.extend(("## Grouped services", ""))
    for service_name, service_type in SERVICES:
        lines.extend((f"### `{service_name}`", "", _summary(service_type), ""))
        for method_name, method in inspect.getmembers(service_type, inspect.isfunction):
            if method_name.startswith("_"):
                continue
            lines.extend(
                (
                    f"#### `{method_name}{_signature(method)}`",
                    "",
                    _summary(method),
                    "",
                )
            )
    return "\n".join(lines).rstrip() + "\n"


if __name__ == "__main__":
    OUTPUT.write_text(generate(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
